[build-system]
requires = ["uv_build>=0.10.4,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
  "ipykernel>=7.4.0",
  "matplotlib>=3.11.1",
  "multisine>=0.1.1",
  "nonlinear-benchmarks",
  "pytest>=9.1.1",
  "ruff>=0.16.3",
  "scipy>=1.17.0",
  "toml-sort>=0.25.0",
]

[project]
name = "best-linear-approximation"
version = "0.1.0"
description = "Estimate nonparametric best linear approximations of nonlinear systems"
readme = "README.md"
authors = [
  { email = "merijn.floren@gmail.com" }
]
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.12"
dependencies = [
  "numpy>=2.0"
]

[project.optional-dependencies]
benchmarks = [
  "nonlinear-benchmarks",
  "scipy>=1.17.0"
]

[project.urls]
Repository = "https://github.com/merijnfloren/best-linear-approximation"
Issues = "https://github.com/merijnfloren/best-linear-approximation/issues"

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "CPY001", # missing-copyright-notice
  "D203", # incorrect-blank-line-before-class
  "D213", # multi-line-summary-second-line
  "N803", # invalid-argument-name
  "N806" # non-lowercase-variable-in-function
]

[tool.ruff.lint.per-file-ignores]
"src/best_linear_approximation/_dataloader.py" = [
  "ANN401", # untyped optional dependency
  "PLC0415" # lazy optional-dependency imports
]
"tests/**/*.py" = [
  "D100", # undocumented-public-module
  "D103", # undocumented-public-function
  "FBT001", # boolean-type-hint-positional-argument
  "INP001", # implicit-namespace-package
  "PLR0913", # too-many-arguments
  "PLR0917", # too-many-positional-arguments
  "N803", # invalid-argument-name
  "S101" # assert
]
